package com.nightreign.relicchecker.gamedata.ranker

// 「增伤排名」配置部分的文案常量表：点号路径 → 文案。
//
// 与 Windows 端 windows/renderer/pages/ranker.js 的 TEXT（按点号路径展开，flattenText）、macOS 端
// RelicCore/BuffLoadout.swift 的 LoadoutText.table **逐键逐字相同**（本表由 ranker.js 的 TEXT 原样导出，按键排序）。
// 三端用同一个摘要锁住：点号路径排序后逐行「路径=文案」、按 UTF-8 字节做 FNV-1a 32 位 = 446c874b，共 346 条
// （:gamedata 测试 RankerTextTest 断言；两端的常量见 ranker_crosscheck.test.mjs 的 TEXT_TABLE_DIGEST）。
// 改任何一句文案都必须三端同时改、同时更新摘要。带 {0} {1} 的是格式串，由 RankerText.fmt 按位置替换。
// skills schemaVersion 3 起多了武器来源标记 weaponSource.*（fixed / pool / poolHint / note，332 → 336 条）：
// 它们属于上半部分的武器选择器，但三端同名同值，也放在这张表里。
// buffs v6 修订的道具等级又多了 goodsLevel.*（tag / hint / note，336 → 339 条，07a69c5e → 41e2ae25）：「道具」分栏里
// 携物知识 2／3 级的行在名字旁标 tag（长按看 hint），分栏说明区给 note。
// 输出手段的类型开关拆成三档（战技 / 魔法 / 祷告，游戏里魔法与祷告是两类）又多了七个键：meansKind.skill / sorcery /
// incantation（开关三档）、meansCard.subtitle（卡片与抽屉的副标题）、meansSearch.placeholder / empty（检索框与空列表）、
// meansSpellFlatNote（选中魔法／祷告时的标记）；pageSubtitle 与 otherInnateNoWeapon 改值（「法术」→「魔法／祷告」），
// 339 → 346 条，41e2ae25 → 446c874b。三档只是界面层的过滤，输出手段与生效判定（appliesTo 的 skill / sorcery /
// incantation）不变；技术说明区（brief.*）里作为统称的「法术」不改。

internal val RANKER_TEXT_TABLE: Map<String, String> = linkedMapOf(
    "accEffectCount" to "{0} 条效果",
    "accFull" to "护符已满",
    "accIntro" to "最多 {0} 个，同一护符不能装两个（护符格数来自游戏文本与用户说明，参数表没有字段）",
    "accPlaceholder" to "选择护符…",
    "accRemove" to "移除",
    "accSlotLabel" to "护符 {0}",
    "accUsedElsewhere" to "（已装备）",
    "activationNeed.activated" to "发动型：只在技艺／绝招／战技发动期间存在",
    "activationNeed.conditional" to "条件型：需满足发动条件（残血、双手持、命中触发…）",
    "activationNeed.equipped" to "条件型：装备中有 {0} 把以上{1}（与出手的武器无关）",
    "badges.accLadder" to "累积阶梯",
    "badges.activated" to "发动型",
    "badges.ally" to "队友增益",
    "badges.allyPair" to "队友那一行",
    "badges.autoInnate" to "当前武器固有，自动列入",
    "badges.blessing" to "武器赐福",
    "badges.conditional" to "条件型",
    "badges.copies" to "按份数叠加",
    "badges.currentSkill" to "当前战技",
    "badges.curse" to "诅咒",
    "badges.deepOnly" to "深夜专属",
    "badges.fixed" to "固定词条",
    "badges.inferredInnate" to "行名推断",
    "badges.inferredSource" to "来源为推断",
    "badges.inferredTiers" to "参数推断，未实测",
    "badges.ladder" to "叠层",
    "badges.outsideWeaponType" to "不在当前武器类别",
    "badges.potency" to "档位{0}",
    "badges.requiresCurse" to "需诅咒",
    "badges.variant" to "按武器类别取一档",
    "brief.activation" to "activation 不是 passive 的条目（条件型／发动型）与需要手动确认的条件，默认不计入：占槽位的栏（武器词条、遗物、护符、当前武器固有）放进来≠条件成立，要单独勾选「条件成立」；不占槽位的「其它增益」栏里勾选本身就是确认；叠层填层数、累积阶梯选层同样算确认。",
    "brief.affixVariant" to "同一遗物词条下挂多档的（数据 affixVariant，{0} 组 {1} 条，例如「出击时的武器，附加…」的 4 档）：游戏按出击武器的类别只生效一档、不能相乘；参数里查不到武器类别到档位的映射，本页默认按第 1 档计算，让你按出击武器选档。",
    "brief.appliesTo" to "生效判定一律按数据的 appliesTo：战技（含战技射出的子弹段）看 skill、魔法看 sorcery、祷告看 incantation。conditional 的机读条件里，持武器的手、出手武器类别（法术按施法器：魔法＝手杖、祷告＝圣印记）、物理攻击类型按当前输出自动判定；子类别按 attackIndex 对所选战技／法术判定；攻击情境用上方的情境勾选；附魔武器限定、需同时使用道具等无法自动判定的要手动确认。",
    "brief.deepWeapon" to "深夜诅咒武器每把 2 条正面词条，其中深夜专属正面词条最多 1 条（6 把最多 {0} 条，按 weaponAffixDeepOnlyPositive 计数）；负面诅咒另按每把 1 条算，不占这个名额，也不计增伤。同一把武器的两条正面词条能否相同（或同一词条的不同档位），参数表里查不到（duplicateWithinWeapon.status={1}），本页只校验总数与深夜专属上限，不按把分配。",
    "brief.direction" to "减益不计入：direction=decrease 的 {0} 条（附加异常时的武器伤害惩罚、降低敌人攻击力等）按 notes.ranking 第②步一律不进乘积；mixed（有增有减，例如附加属性时物理减、属性加）照常计入。",
    "brief.equipped" to "「装备三把以上类别为 X 的武器」判的是装备中的数量，与出手的武器无关，对战技与法术都生效；「提升 X 的攻击力」只对用 X 发动的攻击生效（notes.userQuestions.Q3）。",
    "brief.fill" to "「按推荐填满」只填空着的槽位，顺序是武器词条 → 遗物逐格（最好的固定遗物与贪心自组的合法遗物比较，分数相同取固定遗物）→ 护符；每一步都按「加进去之后的总倍率」取增幅最大的候选，增幅相同取 ID 小的；只算不用确认、不用填层数或选层就会计入的条目，不选条件型。",
    "brief.formula" to "总倍率＝按互斥键去重后，全部计入条目在每个伤害类型上的倍率连乘，再按伤害构成占比加权；攻击力倍率层与最终伤害倍率层相乘，物理子类型倍率只乘对应那一部分；各栏小计同法只算本栏；攻击力加算（点数）只展示、不进连乘。",
    "brief.innate" to "当前武器的固有效果自动列入「其它增益 · 武器固有」：被动的直接计入；条件型默认不计入，要勾选「条件成立」；叠层类默认 0 层，要填层数（notes.ranking 第③步：自动带入不算用户确认）。其它武器的固有效果可以手动勾选。",
    "brief.partial" to "子类别只有部分段命中（requires.subCategoriesAny）时按近似加权：每个伤害类型取 1＋(倍率−1)×命中段占比，占比＝attackIndex 里所选战技／法术带该子类别的段数÷总段数；attackIndex 只给整招各子类别组合的段数、没有逐段对应，所以占比不随上方的分段勾选变化。",
    "brief.relic" to "遗物：普通遗物按「普通 1.03」口径（三条不重复、compatibilityId 两两不同、能分配到槽池模板）；深夜遗物按「深夜正面」口径，并要求 requiresCurse 的词条各配一条负面诅咒池（{0}）里的诅咒（与存档检查的深夜遗物审计同一规则、同一文案）。不足三条时用可落任一槽池、不参与互斥的占位词条补足后再检查。官方固定遗物整件计入；随整件带进来的条件型效果要手动确认。",
    "brief.runStack" to "叠层：{0}。同一阶梯各层互斥、只取当前层；不同阶梯（封印监牢、黑夜入侵者等）按 categoryPriority 判为互不顶替、可以同时生效——参数推断，未实测。",
    "brief.skillAttack" to "「提升战技攻击力」类（子类别 {0}）只作用于战技（含战技的子弹段），不作用于法术与普通攻击；法术吃到的「提升攻击力（XX・战技）」是战技发动后给自己的全伤害增益（sourceSlot=weaponSkill），名字里的「战技」是来源（notes.userQuestions.Q1）。",
    "brief.stacking" to "叠加按 stacking.exclusiveKey：同键只计一份（applyHighest 按 categoryPriority 取数值小的，其余取有效倍率高的，再相同取 spEffectId 小的），不同键相乘。同一个 spEffectId 从多处各拿一份时，spCategory=10（stackSelf）且按 ID 互斥的各份相乘，其余只算一份（多档词条同一词条装两件也只算一份）——都是按 SpEffectParam 参数结构推断，未经木桩实测（stackingRules）。",
    "brief.target" to "作用对象按 notes.ranking 第①步只保留 self 与 ally（ally＝自己与／或附近队友）；同一战技成对的 Self／Allies 两行（selfAllyPair）算施放者自己时只计 Self 那一行，Allies 那一行只在队友施放时计入。",
    "brief.throwInferred" to "appliesTo 对致命一击（throw）的判定是推断，而且与 Paramdex 对 throwAttackParamChange 的字面说明相反（notes.appliesTo）；本页的输出只有战技与法术，不涉及致命一击。",
    "brief.tiers" to "同一词条的不同档位（＋1／＋2、档位1／2／3）是不同的 SpEffect、各有自己的互斥键，本页按相乘计算——参数推断，未实测。",
    "briefHeading" to "口径说明",
    "briefIntro" to "数据集 notes.ranking / stackingRules / notes.userQuestions 的结论简述",
    "briefStack.copies" to "每份 ×{0}、N 份按 N 次方相乘，参数表无上限",
    "briefStack.item" to "{0}：{1}",
    "briefStack.ladder" to "第 n 层取第 n 档（每层约 ×{0}），参数表 {1} 层",
    "briefStack.practical" to "，一局实际上限 {0} 层（×{1}）",
    "briefStack.separator" to "；",
    "briefStack.unit" to "（层数＝{0}）",
    "cardControlsHint" to "条件型效果请在下方勾选「条件成立」；叠层效果在这里填层数、累积阶梯在这里选层、按武器类别取一档的词条在这里选档",
    "characterKinds.Passive" to "被动",
    "characterKinds.Skill" to "技艺",
    "characterKinds.Ultimate" to "绝招",
    "characterNames.Duchess" to "女爵",
    "characterNames.Executor" to "执行者",
    "characterNames.Guardian" to "守护者",
    "characterNames.Ironeye" to "铁之眼",
    "characterNames.Raider" to "无赖",
    "characterNames.Recluse" to "隐士",
    "characterNames.Revenant" to "复仇者",
    "characterNames.Scholar" to "学者",
    "characterNames.Undertaker" to "送葬者",
    "characterNames.Wylder" to "追踪者",
    "characterOther" to "其他角色",
    "checkConflictDetail" to "{0} 不能同时出现",
    "checkConflictTitle" to "同一互斥池",
    "checkDuplicateDetail" to "同一个效果不能在一件遗物上出现两次：{0}",
    "checkDuplicateTitle" to "词条重复",
    "checkPoolDetail" to "{0} 不在当前校验模式的候选词条池",
    "checkPoolTitle" to "不在当前出货池",
    "checkTemplateDetail" to "{0} 无法分配到任一合法三词条槽模板",
    "checkTemplateTitle" to "不符合当前槽池模板",
    "clearButton" to "清空配置",
    "columns.accessory" to "护符",
    "columns.other" to "其它增益",
    "columns.relic" to "遗物",
    "columns.weaponAffix" to "局内武器词条",
    "contextsLabel" to "攻击情境（勾选后，只在该情境成立的倍率才计入）",
    "curseConflictDetail" to "同一互斥池的词条不能同时出现：{0}",
    "curseConflictTitle" to "互斥词条同时出现",
    "curseDuplicateDetail" to "同一词条在一件遗物上重复出现：{0}",
    "curseDuplicateTitle" to "词条重复",
    "curseMismatchDetail" to "第 {0} 行的负面词条不在诅咒池：{1}",
    "curseMismatchTitle" to "负面词条不在诅咒池",
    "curseMissingDetail" to "第 {0} 行的正面词条需要配对负面词条：{1}",
    "curseMissingTitle" to "需诅咒的词条缺少负面词条",
    "cursePairingDetail" to "已按存档检查的深夜遗物审计规则逐行核对：需要诅咒的词条各配一条诅咒池（{0}）里的诅咒，不需要的不带；自组遗物按 3 格计，不涉及具体遗物 ID",
    "cursePairingTitle" to "诅咒配对已校验",
    "curseUnexpectedDetail" to "第 {0} 行的正面词条不需要负面词条，却携带负面词条：{1}",
    "curseUnexpectedTitle" to "多余的负面词条",
    "detailActivation" to "发动条件",
    "detailDesc" to "说明",
    "detailKey" to "互斥键",
    "detailStatus" to "状态",
    "fillButton" to "按推荐填满",
    "fillDone" to "已按推荐填入 {0} 项",
    "fillNote" to "只填空着的槽位：先局内武器词条，再逐格遗物（最好的固定遗物与贪心自组的合法遗物比较，同分取固定遗物），最后护符；每一步取让总倍率增幅最大的候选（同增幅取 ID 小的），不选条件型、叠层与累积阶梯，已选的一律保留",
    "fillNothing" to "没有可填的空槽或可用条目",
    "flatInline" to "攻击力 {0}",
    "goodsFallback" to "道具 #{0}",
    "goodsLevel.hint" to "学者的能力「携物知识」把道具提升到这一级后才有这条效果；其它角色只有 1 级。",
    "goodsLevel.note" to "道具的 2／3 级效果来自学者的能力「携物知识」，未升级的道具只有 1 级效果。",
    "goodsLevel.tag" to "携物知识 {0} 级",
    "groupAutoInnate" to "当前武器自带（自动列入）",
    "groupOtherInnate" to "其它武器的固有效果（手动勾选）",
    "groupUnknownSkill" to "未标明战技",
    "hand.1" to "右手",
    "hand.2" to "左手",
    "handHelp" to "按增益的 appliesToDetail.requires.hand 判定当前手（只作用于另一只手的增益不计入），默认按右手计算",
    "handLabel" to "武器槽",
    "innateRemove" to "不计入",
    "innateRestore" to "计入",
    "ladderTierCount" to "共 {0} 层，选中后选层",
    "loadoutMissing" to "增益数据缺少配置页需要的字段（slotRules／appliesTo，需 schemaVersion 6）",
    "meansCard.subtitle" to "搜索战技、魔法或祷告（中文／英文名都可）；战技再选一把武器",
    "meansKind.incantation" to "祷告",
    "meansKind.skill" to "战技",
    "meansKind.sorcery" to "魔法",
    "meansSearch.empty" to "没有匹配的输出手段",
    "meansSearch.placeholder" to "搜索战技 / 魔法 / 祷告名称",
    "meansSpellFlatNote" to "魔法／祷告的段只用固定值",
    "modeTrimmed" to "切到常规：已去掉 {0} 条深夜专属／超出常规上限的武器词条，深夜遗物格已清空",
    "noData" to "数据未内置",
    "noteCopiesSingle" to "装了 {0} 份：同一 spEffectId 多份只算一份（stackingRules：只有按 ID 互斥的 stackSelf 才各份相乘）",
    "noteCopiesStackSelf" to "stackSelf：{0} 份各自相乘（stackingRules 第 2 条，参数推断，未实测）",
    "optionInactive" to "（不生效）",
    "optionPotential" to "（{0}，条件成立时 {1}）",
    "optionScore" to "（{0}）",
    "otherAutoInnate" to "当前武器固有，自动列入",
    "otherEmpty" to "这一组里没有能增伤的条目",
    "otherGroups.character" to "角色",
    "otherGroups.consumable" to "道具",
    "otherGroups.other" to "其它",
    "otherGroups.permanent" to "永久强化",
    "otherGroups.runStack" to "局内叠层",
    "otherGroups.spellBuff" to "增益法术",
    "otherGroups.weaponInnate" to "武器固有",
    "otherGroups.weaponSkill" to "战技自增益",
    "otherInnateHint" to "当前武器的固有效果自动列入（取消勾选可排除）：被动的直接计入；条件型默认不计入，要勾选「条件成立」；叠层类默认 0 层，要填层数",
    "otherInnateNoWeapon" to "魔法与祷告没有出手武器，这里只有需手动勾选的固有效果",
    "otherIntro" to "不占槽位，按需勾选；勾选即视为条件成立，叠层类勾选后先填一局实际上限、累积阶梯先选最高层（都可以改）",
    "otherSearch" to "搜索增益名称、来源或 SpEffect 行号",
    "outputClass.incantation" to "祷告",
    "outputClass.skill" to "战技",
    "outputClass.sorcery" to "魔法",
    "overviewCount" to "共 {0} 条（每条单独按「条件全部成立」算：叠层取一局实际上限、没有上限的按 1 层，累积阶梯与多档词条按每一层／每一档自己算；未去重、未连乘，只供查阅）。",
    "overviewMore" to "再显示 {0} 条（剩余 {1} 条）",
    "overviewNext" to "下一页",
    "overviewNoMatch" to "没有匹配的条目",
    "overviewOneStack" to "按 1 层",
    "overviewOneStackHelp" to "叠层条目没有实际上限（practicalMaxStacks／uiLabelMax 都没有），一览只按 1 层算；在栏里填层数后按实际层数",
    "overviewPage" to "第 {0} / {1} 页 · 每页 {2} 条",
    "overviewPill" to "查阅用",
    "overviewPrev" to "上一页",
    "overviewSearch" to "搜索增益名称、来源或 Paramdex 行名",
    "overviewTitle" to "全部增益一览",
    "pageSubtitle" to "选一个战技、魔法或祷告，再自己组一套局内配置：武器词条、遗物、护符与其它增益，看总增伤",
    "pageTitle" to "增伤排名",
    "pickerDone" to "完成",
    "potentialOneStack" to "条件成立时（未设上限，按 1 层）{0}",
    "potentialText" to "条件成立时 {0}",
    "questionsTitle" to "数据集的问答（notes.userQuestions，{0} 条）",
    "reasonAllyPair" to "同一战技的队友那一行（selfAllyPair.role=ally）：施放者自己吃不到，只在队友施放、落到自己身上时计入",
    "reasonDecrease" to "direction=decrease：这是减益（降低自己的伤害、降低敌人攻击力等），按 notes.ranking 第②步只保留 increase／mixed，不计入增伤",
    "reasonDupKey" to "与「{0}」同属互斥键 {1}，同键只取一份（取有效倍率高的）",
    "reasonDupPriority" to "与「{0}」同属互斥键 {1}（applyHighest）：按 categoryPriority 取数值小的那份（{2} 优先于 {3}），本条被压掉",
    "reasonNeutral" to "对当前伤害构成没有增益（倍率 ×1、没有正的攻击力加算）",
    "reasonNoDamage" to "不含计入伤害的倍率字段",
    "reasonRelicInvalid" to "所在的自组遗物不合法，整件不计入",
    "reasonTarget" to "作用对象不是自己（target={0}）",
    "reasonTierNone" to "累积阶梯还没选层（选层即视为条件成立）",
    "reasonTierOff" to "累积阶梯只算选中的那一层（当前选第 {0} 层）",
    "reasonVariantOff" to "同一遗物词条的 {0} 档按出击武器类别只生效一档（数据 affixVariant），当前按第 {1} 档计算",
    "reasonZeroStacks" to "层数为 0，不计入（填层数即视为条件成立）",
    "relicAffixEmpty" to "（空）",
    "relicAffixPickerHint" to "按对当前输出的有效倍率排序；红字＝选上后这件遗物不合法的原因",
    "relicCardDeep" to "深夜遗物 {0}",
    "relicCardNormal" to "普通遗物 {0}",
    "relicColors.0" to "红",
    "relicColors.1" to "蓝",
    "relicColors.2" to "黄",
    "relicColors.3" to "绿",
    "relicColors.4" to "白",
    "relicCountedLabel" to "计入情况（非增伤词条只显示不计入）",
    "relicCurseLabel" to "诅咒（不计增伤，但要占位）",
    "relicCurseNote" to "诅咒只占位，不计增伤",
    "relicCursePlaceholder" to "（未选诅咒）",
    "relicCurseSearch" to "搜索诅咒",
    "relicEffectsLabel" to "词条",
    "relicEmpty" to "未选择词条",
    "relicFixedNone" to "数据未内置深夜固定遗物，深夜遗物格只能自组",
    "relicFixedPlaceholder" to "选择官方固定词条遗物…",
    "relicFixedSearch" to "搜索固定遗物名称或词条",
    "relicFixedSubtitle" to "{0}色 · 遗物 #{1}",
    "relicFixedUsedElsewhere" to "（已在别的遗物格）",
    "relicFixedValid" to "官方固定词条遗物：整件按数据的 spEffectIds 计入，非增伤词条只显示",
    "relicIntro" to "常规 {0} 个普通遗物格；深夜另加 {1} 个深夜遗物格。每格二选一：官方固定词条遗物整件选入，或按词条检查页的规则自组不超过 3 条（普通遗物用「普通 1.03」口径，深夜遗物用「深夜正面」口径＋诅咒配对，实时检查合法性）",
    "relicInvalid" to "该遗物组合不合法",
    "relicNoCatalog" to "词条库未载入，无法自组遗物",
    "relicNonDamage" to "不计增伤",
    "relicPartial" to "预检通过：已选 {0} 条，其余 {1} 条可填任意不增伤、不冲突的合法词条",
    "relicPickAffix" to "选择词条…",
    "relicPlaceholderAffix" to "其余不增伤词条",
    "relicRemove" to "移除",
    "relicRowLabel" to "词条 {0}",
    "relicSearch" to "搜索词条名称、分类或 ID",
    "relicStatus.empty" to "空",
    "relicStatus.fixed" to "固定遗物",
    "relicStatus.invalid" to "不合法",
    "relicStatus.partial" to "预检通过",
    "relicStatus.valid" to "合法",
    "relicType.custom" to "自组",
    "relicType.empty" to "空",
    "relicType.fixed" to "固定遗物",
    "relicTypeAria" to "遗物来源",
    "relicUnknownEffectDetail" to "以下词条 ID 不在词条索引中：{0}",
    "relicUnknownEffectTitle" to "存在未知词条 ID",
    "relicUnnamedEffect" to "词条 #{0}",
    "relicValidDeep" to "合法：正面词条按「深夜正面」口径通过，诅咒配对已逐行校验",
    "relicValidNormal" to "合法：三条词条按「普通 1.03」口径通过",
    "requireAttached" to "只对带这条词条的那把武器生效，需确认",
    "requireContext" to "只在「{0}」时成立（在「攻击情境」里勾选）",
    "requireGoods" to "需同时使用道具：{0}，需确认",
    "requireHand" to "只作用于{0}武器（当前为{1}）",
    "requireImbued" to "只对附加了属性的那把武器生效（附魔／油脂／出击时附加），需确认",
    "requireManual" to "数据判定为有条件生效：{0}，需确认",
    "requirePhysical" to "只作用于{0}攻击",
    "requirePhysicalFail" to "只作用于{0}攻击（当前构成里没有这一类）",
    "requireSubsAll" to "所选{0}的 {1} 段都带子类别 {2}",
    "requireSubsFail" to "所选{0}的命中段都不带子类别 {1}",
    "requireSubsPartial" to "所选{0}只有 {1}/{2} 段带子类别 {3}：按 1＋(倍率−1)×{1}/{2} 近似加权（段数取 attackIndex 对整招的统计，与上方分段勾选无关）",
    "requireSubsUnknown" to "attackIndex 里没有所选{0}，子类别 {1} 无法自动判定，需确认",
    "requireUnknown" to "数据要求 {0}，本页无法自动判定，需确认",
    "requireWepType" to "只对用{0}发动的攻击生效（当前为{1}）",
    "requireWepTypeNoWeapon" to "只对用{0}发动的攻击生效（当前没有选武器）",
    "runMode.deep" to "深夜",
    "runMode.normal" to "常规",
    "runModeAria" to "常规或深夜",
    "runModeHint" to "常规：武器词条最多 {0} 条、遗物 {1} 件；深夜：武器词条最多 {2} 条（其中深夜专属最多 {3} 条）、遗物 {4} 件（普通 {5} ＋ 深夜 {6}）",
    "runModeLabel" to "出击模式",
    "schemaTooOld" to "增益数据是 schemaVersion {0}：本页按 v6 的 appliesTo / slotRules / exclusiveKey 组配置，旧数据缺这些字段，结果不可信",
    "searchPlaceholder" to "搜索名称",
    "selectUse" to "选用",
    "showInactive" to "显示不生效项",
    "showInactiveHelp" to "appliesTo 判为不生效（或条件不满足）的条目默认隐藏；打开后虚化显示并写明原因",
    "spellHandNote" to "施法器同样握在左右手之一：按 appliesToDetail.requires.hand 判定，只作用于另一只手的增益不计入；武器词条栏按施法器（魔法＝手杖、祷告＝圣印记）的类别过滤。",
    "stackHintCopies" to "每份 ×{0}，N 份按 ×{0}^N 相乘（参数表无上限）",
    "stackHintGrace" to "本局新发现的赐福数",
    "stackHintLabel" to "游戏文本备有『＋1』到『＋{0}』的标签",
    "stackHintLadder" to "阶梯：第 n 层取 tierMultipliers[n-1]，参数表共 {0} 层，各层互斥只取当前层",
    "stackHintPractical" to "一局实际最多 {0} 层，可以填更多但会提示",
    "stackLabel" to "层数",
    "stackLabelCopies" to "份数",
    "stackOverCeiling" to "份数按上限 {0} 计算",
    "stackOverLabel" to "游戏文本只备到＋{0}，更多层数按同一倍率外推（未实测）",
    "stackOverParam" to "参数表只有 {0} 层，按第 {0} 层计算",
    "stackOverPractical" to "填了 {0} 层，超过一局实际能叠到的 {1} 层（{2}）",
    "states.context" to "需勾选攻击情境",
    "states.counted" to "计入",
    "states.duplicate" to "同键不叠加",
    "states.neutral" to "对当前构成无增益",
    "states.no" to "不生效",
    "states.noDamage" to "不含伤害倍率",
    "states.pending" to "条件未确认",
    "states.relicInvalid" to "遗物不合法",
    "states.tierOff" to "未选的层",
    "states.variantOff" to "未选的档",
    "states.zeroStacks" to "层数为 0",
    "stepDown" to "减少",
    "stepUp" to "增加",
    "stepperAria" to "数量",
    "summaryColumnNote" to "总倍率＝按互斥键去重后逐伤害类型连乘，再按伤害构成占比加权；各栏小计只算本栏（同法），不一定相乘等于总倍率",
    "summaryContribution" to "贡献",
    "summaryCount" to "{0} 条",
    "summaryCounted" to "当前生效条目（{0}）",
    "summaryEmpty" to "还没有放入任何增益。可以在下面各栏里挑选，或点「按推荐填满」。",
    "summaryFlat" to "另有攻击力加算",
    "summaryFlatNote" to "攻击力加算（点数）没有绝对攻击力就折不成倍率，只按占比加权展示，不进连乘",
    "summaryGain" to "相对提升",
    "summaryHeading" to "汇总",
    "summaryHiddenNo" to "另有 {0} 条对当前输出不生效（打开「{1}」查看原因）。",
    "summaryNoComposition" to "先勾选至少一段带伤害的命中，才能计算倍率",
    "summaryRemove" to "移除",
    "summarySubtotals" to "各栏小计（本栏单独计算）",
    "summaryTick" to "条件成立",
    "summaryTickHelp" to "条件型：勾上表示你确认这个条件在出手时成立，才计入总倍率",
    "summaryTotal" to "总倍率",
    "summaryUncounted" to "选了但未计入（{0} 条）",
    "tierLabel" to "第 {0} 层",
    "tierLabelThreshold" to "第 {0} 层（累积 {1}）",
    "tierNone" to "不计",
    "tierSelectLabel" to "层",
    "usageAccessory" to "护符",
    "usageDeepOnly" to "深夜专属",
    "usageRelic" to "遗物",
    "usageWeaponAffix" to "武器词条",
    "variantLabel" to "档",
    "variantNoMapping" to "参数里查不到「出击武器类别 → 档位」的映射（词条只有一个按武器派发的行，没有任何列指向这几档），默认按第 1 档计算，请按出击武器自行选档",
    "variantOption" to "第 {0} 档{1}",
    "variantRates" to "（{0}）",
    "verdict.conditionalMet" to "生效（条件已满足）",
    "verdict.needsUser" to "条件生效",
    "verdict.no" to "不生效",
    "verdict.partial" to "部分段生效",
    "verdict.yes" to "生效",
    "verdictMissing" to "数据未给出这类输出的 appliesTo，按不生效处理",
    "verdictNoFallback" to "数据判定对这类输出不生效",
    "violationAccessory" to "护符 {0} 个，超过上限 {1} 个",
    "violationAccessoryDuplicate" to "同一护符不能装两个",
    "violationDeepOnly" to "深夜专属正面词条 {0} 条，超过上限 {1} 条（每把武器最多 1 条）",
    "violationDeepOnlyInNormal" to "常规模式没有深夜专属词条（当前选了 {0} 条）",
    "violationRelic" to "{0}：{1}",
    "violationWeaponAffix" to "局内武器词条 {0} 条，超过{1}上限 {2} 条",
    "waCapReached" to "已达上限",
    "waCopiesHint" to "同一条词条装多份：按 ID 互斥的 stackSelf 各份相乘，其余只算一份（stackingRules 第 2 条，参数推断，未实测）",
    "waDeepOnlyCapReached" to "深夜专属已达上限",
    "waDeepOnlyUsage" to "深夜专属 {0} / {1}",
    "waEmpty" to "当前筛选下没有能增伤的武器词条",
    "waFilterAll" to "全部类别",
    "waFilterAria" to "武器类别过滤",
    "waFilterNone" to "当前输出没有武器类别，显示全部",
    "waFilterWeapon" to "当前武器类别（{0}）",
    "waIntro" to "局内捡到的武器随机带的词条；{0} 把武器的词条全局生效。按对当前输出的有效倍率排序",
    "waNotInMode" to "常规模式没有这条（只出现在深夜诅咒武器上）",
    "waSearch" to "搜索武器词条",
    "waTierHint" to "同一词条的不同档位各自一个互斥键，按相乘计算（参数推断，未实测）",
    "waUsage" to "已用 {0} / {1}",
    "warnCopiesSingle" to "同一效果装了多份，按数据 stackingRules 只算一份（只有按 ID 互斥的 stackSelf 才各份相乘）：{0}",
    "warnCopiesStackSelf" to "同一效果装了多份，按 stackSelf 各份相乘（stackingRules 第 2 条，参数推断，未实测）：{0}",
    "warnDuplicateKey" to "互斥键 {0}：{1} 份只计 1 份（{2}）",
    "warnExclusivity" to "「{0}」同属遗物互斥组 exclusivityId={1}：按参数推断分装在不同遗物上时只有一条生效，本页仍分别计入（未实测）",
    "warnFixedDuplicate" to "同一件固定遗物只能装备一件：{0}",
    "warnLadders" to "不同叠层阶梯同时生效（{0}）：各阶梯 categoryPriority 不同、按参数结构判为互不顶替、结果相乘，未实测",
    "warnPriority" to "互斥键 {0}（applyHighest）：按 categoryPriority 取数值小的「{1}」，压掉 {2}",
    "warnTiers" to "「{0}」的不同档位同时计入（{1}），各自独立相乘：参数推断，未实测",
    "weaponSource.fixed" to "固定战技",
    "weaponSource.note" to "武器列表含固定带这个战技的武器与局内战技池能抽到它的武器；动作套按这一把武器实解。",
    "weaponSource.pool" to "局内可抽到",
    "weaponSource.poolHint" to "局内掉落的这把武器有机会抽到这个战技（按战技池权重）",
    "wepTypeFallback" to "类别 {0}",
)
